### ISSUE TITLE
incompatibility with Brothers Johnson Unshaders

### ISSUE THREAD

**Issue by 4rz0** [lumien231/Hardcore-Darkness#11]
I'm not quite sure if it's possible to fix that, but if I use HardcoreDarkness with [Brothers Johnson Unshaders](http://brothersjohnsongames.com/brothers-johnson-unshaders/), minimum sky lighting resets to default. Minimum block lighting is still dark.

I wouldn't mind removing parts of the shader pack if necessary, I just don't know which part affects the mod.

**Comment by lumien231** [comment]
Shaders in general do not work with Hardcore Darkness because the rendering changes they do.

**Comment by 4rz0** [comment]
Thanks, I'll see what happens if I remove the shader-part from the ressource-pack.

**Comment by 4rz0** [comment]
For anyone who has the same "problem":
Inside the ressource pack, there's a folder `assets\minecraft\mcpatcher\lightmap`, if this is removed, HardcoreDarkness works as it should.

**Comment by lumien231** [comment]
Oh i thought you were talking about actual shaders^^. Yeah for resource packs you have to remove the custom lightmap.
