### ISSUE TITLE
Add support for the Calendar API

### ISSUE THREAD

**Issue by Sunconure11** [lumien231/Hardcore-Darkness#13]
https://github.com/CallMeFoxie/Calendar/tree/1.7.10

This API cropped up recently, and I suggest you check it out for 1.7.10 and 1.8 builds of your mod, so lighting based on the moon cycle can be in sync with other mods that use it, or plan to use it (Stellar Skies, due to its longer lunar cycle, would be a good example)

**Comment by lumien231** [comment]
I don't use any time related methods in HardcoreDarkness, if mods like these don't patch vanilla methods so that they retain their meaning (Getting the moonphase) i can't really do anything about that.

**Comment by Sunconure11** [comment]
Alright.

**Comment by PitchBright** [comment]
There's nothing the end-user can do to make the two mods work together. HardcoreDarkness calls info from a method getCurrentMoonPhaseFactorBody() in the World class for it's Moon Phase info, and StellarSky uses a method getMoonPhase() in the WorldProvider class.

I think there's differing opinions on which one is the correct one to use.

**Comment by lumien231** [comment]
I expect vanilla methods to work how they do in vanilla.
