### ISSUE TITLE
Configurable moon phase brightness

### ISSUE THREAD

**Issue by Phoenospace** [lumien231/Hardcore-Darkness#17]
Add configuration options to control the brightness of moonlight when skylight based on moon phase is enabled, i.e. a multiplier value to halve (or third, etc) the brightness of the sky light at night, for greater control over difficulty.

**Comment by Terpo** [comment]
Working with the 1.11 version of the mod and this is something that I'm really missing at this point. In combination with InControl from McJty you could do really interesting spawn mechanics.

**Comment by lumien231** [comment]
Added in 1.9
