### ISSUE TITLE
Perpetual total darkness

### ISSUE THREAD

**Issue by liorrozen** [lumien231/Hardcore-Darkness#25]
Hi, 

I'm using this mod in the [invasion modpack (v1.0.5)](https://mods.curse.com/modpacks/minecraft/254433-invasion) running **on a server** and I'm getting total darkness on every night. This does not reproduce in a single player world.

- MC version 1.10.2
- Forge version 12.18.3.2254
- Perpetual total darkness using `HardcoreDarkness-MC1.10.2-1.9.jar`
- Only a single total dark night using `HardcoreDarkness-MC1.9.4-1.8.jar` (this is what I expect)

Here are the relevant config settings (defaults for the pack) - 

```
# Configuration file

settings {
    ...
    # 0: No minimum sky & block light, 1: No minimum block light, 2: Skylight is dependent on moon phase
    I:Mode=2

    # In mode 2 this list defines how much skylight there is when 0%/25%/50%/75%/100% of the moon is visible. (Values go from 0 (Total Darkness) to 1 (Total Brightness)).
    D:MoonLightList <
        0.0
        0.075
        0.15
        0.225
        0.3
     >
}
```

Even when setting all values in `MoonLightList` to 1 the nights were 100% dark. It seems that on a server these values are ignored.

Please let me know if there is any other relevant information I can provide.

**Comment by lumien231** [comment]
The server overrides the clients configs so could you post the server config please?

**Comment by liorrozen** [comment]
@lumien231 The snippet I gave was from the server config.

Thanks for the quick response :)

**Comment by Darkosto** [comment]
Hey @lumien231 any chance you were able to investigate this? :) 

Hope you're doing well! :D

**Comment by lumien231** [comment]
Does this still happen on 1.0.6 ? I can't reproduce this there.

**Comment by Darkosto** [comment]
Honestly, any of the testing I've done from pre-release through 1.0.6 hasn't produced this issue. I'm not too sure how it could be happening for others. I run a windows server myself, is it possible it only happens on a Linux OS?

**Comment by liorrozen** [comment]
@Darkosto @lumien231 - Can reproduce this using version 1.0.7 of the pack. I **am** running the server on linux in a docker container, I noticed that the config files had windows line-ending characters.

Is there any other info I can provide that might be useful? 
Hardcore-Darkness doesn't appear to have changed, but the forge version did... coincidence? (* raised eyebrow *)

**Comment by liorrozen** [comment]
Hi folks, just wanted to add here that while watching [Direwolf20's invasion series](https://www.youtube.com/playlist?list=PLaiPn4ewcbkHXN2aqOccduztk2ezCz0XI), it appears that in at least the past 7 episodes, every night has been 100% dark - exactly the same as I am experiencing.

**Comment by lumien231** [comment]
So yeah, when i try Invasion with a linux server i get the same issue.

**Comment by Darkosto** [comment]
Ahh! There's the issue. I use a windows server for most of my testing.

**Comment by WesCook** [comment]
I can confirm this issue on a Linux server.  Did not show itself in singleplayer (Windows).

Downgrading to 1.9.4-1.8 seems to have solved it.
