### ISSUE TITLE
[Feature Suggestion] Dimension Settings

### ISSUE THREAD

**Issue by BonesTheRabbit** [lumien231/Hardcore-Darkness#3]
Hello! Was just throwing forward the idea that mode settings function on a dimension basis. Maybe via some kind of whitelist or somesuch? Hope that I'm not a bother in putting this forward. Great mod, either way. Cheers! ^ ^ ;

**Comment by Lanse505** [comment]
@lumien231 Is this being implemented or forgotten? I'm currently using Hardcore-Darkness in my pack as a Major-feature but I'd like to avoid using the Hardcore Darkness in mod in the Nether seeing as it makes the Nether Un-playable seeing as you just die.

**Comment by lumien231** [comment]
@Lanse505 Not sure why you "just die" in the nether considering it's fairly bright there due to all the lava. Also there already is a config option for the nether.

**Comment by BonesTheRabbit** [comment]
I originally put forth the suggestion because of the Witchery mod. There's a nightmare dimension there which is not only pitch black, but also precludes bringing items like torches, because you're essentially an astral projection.

**Comment by lumien231** [comment]
Added in 1.7.
