### ISSUE TITLE
Dark Nether turning off after reconnect

### ISSUE THREAD

**Issue by xhatz** [lumien231/Hardcore-Darkness#32]
Hello!

I've spotted that bug since a few time already, but though it would get fixed, and I didn't had the idea of coming to post it here haha, but since it's still here, I make this post to inform you!

When you set the Mode to 2 (depending on moon phase), and go to the nether, it is fine, and it works... but! After disconnecting and connecting, the brightness gets reset and the player can see everything (no more dark spots).

I don't know if it's doing the same with other modes, but yeah...

Thank you for this cool mod still, loving it for realistic packs!

**Xhatz**

**Comment by lumien231** [comment]
Whoops, this is already fixed. Just forgot to actually release a version with the fix 👍 . Will release one today.
