### ISSUE TITLE
Ender IO helmets with night vision upgrade don’t work with Hardcore Darkness

### ISSUE THREAD

**Issue by Dimentive** [lumien231/Hardcore-Darkness#46]
When wearing a dark helmet, end helmet, or stellar helmet with the night vision upgrade from [Ender IO](https://www.curseforge.com/minecraft/mc-mods/ender-io), everything is still just as dark as it was before.

This upgrade does not give you the night vision effect, so this is presumably why. I don’t know how the helmet works normally, though.

# Versions

**Minecraft:** 1.12.2
**Forge:** 14.23.5.2847
**Hardcore Darkness:** 2.0
**Ender IO:** 5.1.52

**Comment by mxnmnm** [comment]
lol u gotta turn on the button to enable the night vision

**Comment by Dimentive** [comment]
_Oh._
