### ISSUE TITLE
[Enhancement] Take moon phase into account

### ISSUE THREAD

**Issue by BarbasTheDog** [lumien231/Hardcore-Darkness#6]
If you ever played Better Than Wolves, you know what I'm talking about.
Instead of it being equally pitch black both inside caves and outside, take the sky light into consideration, but make it dependant on the moon phase.

New moon  = pitch black
Full mooon = visible enough when in direct view of the sky.

Just something to make it a bit more immersive.

**Comment by lumien231** [comment]
That's exactly what the most recent version added.
